image: registry.gitlab.com/ps2max/ps2sdk:latest

stages:
  - build

build:
  stage: build
  script:
    - make clean all
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - lang/
    - licenses/
    - PS2Ident.elf
    - PS2Ident.db
    - README.md
    - changelog.txt
