image: registry.gitlab.com/ps2max/ps2sdk:latest

stages:
  - build

build:
  stage: build
  script:
    - make clean all
    - cp PS2Ident_packed.elf Release/PS2Ident.elf
    - cp README.md Release/README.md
    - cd Release/
    - zip -r [$(date +'%y%m%d')]PS2Ident-0835-bin.zip lang/ license/ PS2Ident.db changelog.txt README.md PS2Ident.elf
  artifacts:
    paths:
    - Release/*.zip
