name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    name: PS2Ident compilation
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    # instead of "ps2dev/ps2dev:latest" you can use different tags, for example for old projects you can use "ps2dev/ps2dev:v1.0"
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip

    - uses: actions/checkout@v4

    - name: Get short SHA and repository name
      id: slug
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"

    - name: Compile PS2TOOL version
      run: |
        make clean
        make DEBUG=1 DSNET_HOST_SUPPORT=1

    - name: Upload PS2TOOL artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}-PS2TOOL
        path: |
          PS2Ident_np.elf
          PS2Ident.db
          README.md
          changelog.txt
          LICENSE_OFL.txt
          *.ttf

    - name: Compile project
      run: |
        make clean
        make
    # commands for compiling your project

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}
        path: |
          PS2Ident.elf
          PS2Ident.db
          README.md
          changelog.txt
          LICENSE_OFL.txt
          *.ttf

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4

    - name: Get short SHA and repository name
      id: slug
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"

    - name: Download PS2Ident artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}
        path: PS2Ident

    - name: Prepare PS2Ident archive
      run: |
        7z a ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}.7z PS2Ident/*

    - name: Download PS2Ident for PS2TOOL artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}-PS2TOOL
        path: PS2Ident-PS2TOOL

    - name: Prepare PS2Ident for PS2TOOL archive
      run: |
        7z a ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}-PS2TOOL.7z PS2Ident-PS2TOOL/*

    - name: Create pre-release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "Development build"
        files: |
          ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}.7z
          ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}-PS2TOOL.7z

    - name: Create Tagged Release Draft
      if: startsWith(github.ref, 'refs/tags/v')
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "stable"
        draft: true
        files: |
          ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}.7z
          ${{ steps.slug.outputs.REPOSITORY_NAME }}-${{ steps.slug.outputs.sha8 }}-PS2TOOL.7z

